# Generated by Django 3.2.7 on 2021-09-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_alter_comment_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='photo.jpg', upload_to='profile_pictures/'),
        ),
    ]
